theme: jekyll-theme-architect
enableGitInfo: true
frontmatter:
  date:
  - :git
  - date
  - publishDate
  - lastmod
  expiryDate:
  - expiryDate
  lastmod:
  - :git
  - lastmod
  - date
  - publishDate
  publishDate:
  - publishDate
  - date